# -*- coding: utf-8 -*-
"""AmazonPriceTracker.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nVUjiTxEz8sgpcCFrraovefu3NsxRQXe
"""

import requests
from bs4 import BeautifulSoup
import smtplib
import time 

URL = 'https://www.amazon.com/XG49VQ-Curved-Gaming-FreeSync-Monitor/dp/B07PZR2YY4/ref=sr_1_10?keywords=Asus+Rog&qid=1568506508&s=electronics&sr=1-10'

headers = {
    "User-Agent": 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.75 Safari/537.36'}

def check_price():

  page = requests.get(URL, headers = headers)

  soup = BeautifulSoup(page.content, 'html.parser')
  soup2 = BeautifulSoup(soup.prettify(), 'html.parser')
  
  title = soup2.find(id = "productTitle").get_text()
  title = title.strip()
  price = soup2.find(id = "priceblock_ourprice").get_text()
  converted_price = float(price[1:])
  
  if(converted_price < 869.00):
     send_mail()

  print(converted_price)
  print(title.strip())
  
  if(converted_price < 889.00):
     send_mail()
  
def send_mail():
  server = smtplib.SMTP('smtp.gmail.com', 587)
  server.ehlo()
  server.starttls()
  server.ehlo()
  server.login('youremail', 'yourpassword')
  
  subject = 'Price fell down!'
  body = 'Check Out Link:', URL 
  
  msg = f"Subject: {subject}\n\n{body}"
  
  server.sendmail('senderemail', 
                   'receiveremail', 
                   msg)
  
  print('HEY EMAIL HAS BEEN SENT!!')
  
  server.quit() 
  
while(True):  
    check_price()
   # time.sleep(84600)